---
run:
  concurrency: 6
  deadline: 5m
linters:
  disable-all: true
  enable:
    # - deadcode
    - depguard
    - gofmt
    - typecheck
    - varcheck
    # - dupl
    # - errcheck
    # - gochecknoglobals
    # - gochecknoinits
    # - goconst
    # - gocritic
    # - gocyclo
    # - goimports
    # - golint
    # - gosec
    # - govet
    # - ineffassign
    # - interfacer
    # - lll
    # - maligned
    # - misspell
    # - nakedret
    # - prealloc
    # - scopelint
    # - staticcheck
    # - structcheck
    # - unconvert
    # - unparam
