branches:
  - master
  - auto
  - try

host:
  distro: fedora/28/atomic
  specs:
     ram: 8192
     cpus: 4
packages:
    - podman
required: true
timeout: 45m

tests:
  - CONTAINER_RUNTIME="podman" sh .papr_prepare.sh

context: "FAH28"
---

host:
  distro: centos/7/atomic/smoketested
  specs:
     ram: 8192
     cpus: 4
extra-repos:
    - name: epel
      metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
      gpgcheck: 0
    - name: cri-o
      baseurl: https://cbs.centos.org/repos/virt7-container-common-candidate/$basearch/os
      gpgcheck: 0

required: true
timeout: 45m

tests:
  - sh .papr_prepare.sh

context: "CAH smoketested"


---

inherit: true
host:
    distro: fedora/28/cloud/pungi
    specs:
        ram: 8192
        cpus: 4
extra-repos:
    - name: crio_copr
      baseurl: https://copr-be.cloud.fedoraproject.org/results/baude/Upstream_CRIO_Family/fedora-28-x86_64/
      gpgcheck: 0
packages:
    - podman
    - buildah
tests:
    - CONTAINER_RUNTIME="podman" sh .papr_prepare.sh
required: false
context: "Fedora fedora/28/cloud Podman"
