branches:
  - master
  - auto
  - try

host:
  distro: fedora/26/atomic
  specs:
     ram: 8192

required: true

timeout: 45m

tests:
  - CRIO_ROOT=/var/tmp/checkout KPOD_BINARY=/usr/bin/kpod CONMON_BINARY=/usr/libexec/crio/conmon PAPR=1 sh .papr.sh

---

inherit: true
host:
  distro: centos/7/atomic/alpha
  specs:
     ram: 8192

context: centos/7/atomic/alpha
