branches:
  - master
  - auto
  - try

host:
  distro: fedora/27/atomic
  specs:
     ram: 8192
     cpus: 4

required: true
timeout: 45m

tests:
  -  sh .papr_prepare.sh

---

inherit: true
host:
  distro: centos/7/atomic/smoketested
  specs:
     ram: 8192
     cpus: 4
extra-repos:
    - name: epel
      metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
      gpgcheck: 0
    - name: cri-o
      baseurl: https://cbs.centos.org/repos/virt7-container-common-candidate/$basearch/os
      gpgcheck: 0

context: centos/7/atomic/smoketested
