branches:
  - master
  - auto
  - try

cluster:
  hosts:
    - name: testnode
      distro: fedora/27/atomic
      specs:
        ram: 8192
        cpus: 4
  container:
    image: registry.fedoraproject.org/fedora:27

required: true
timeout: 45m

tests:
  # Docker's iptables rules can conflict with podman; though long term we
  # are going to have to make the two always work together
  - ssh testnode /bin/sh -c 'systemctl stop docker && rpm-ostree override remove docker{,-common,-rhel-push-plugin} cockpit-docker'
  - ./.papr-reboot-wait.sh testnode
  - "scp .papr_prepare.sh testnode: && ssh testnode ./.papr_prepare.sh"

context: "FAH27"
---

inherit: true
host:
  distro: centos/7/atomic/smoketested
  specs:
     ram: 8192
     cpus: 4
extra-repos:
    - name: epel
      metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
      gpgcheck: 0
    - name: cri-o
      baseurl: https://cbs.centos.org/repos/virt7-container-common-candidate/$basearch/os
      gpgcheck: 0

context: "CAH smoketested"

tests:
  - CONTAINER_RUNTIME=docker ./.papr_prepare.sh

---

inherit: true
host:
    distro: fedora/27/cloud/pungi
    specs:
        ram: 8192
        cpus: 4
extra-repos:
    - name: crio_copr
      baseurl: https://copr-be.cloud.fedoraproject.org/results/baude/Upstream_CRIO_Family/fedora-27-x86_64/
      gpgcheck: 0
packages:
    - podman
    - buildah
tests:
    - ./.papr_prepare.sh
required: false
context: "Fedora fedora/27/cloud Podman"
