branches:
  - master
  - auto
  - try

host:
  distro: fedora/28/atomic
  specs:
     ram: 8192
     cpus: 4
required: true
timeout: 90m

tests:
  - CONTAINER_RUNTIME="podman" sh .papr_prepare.sh

artifacts:
  - build.log

context: "FAH28"
---

host:
  distro: centos/7/atomic/smoketested
  specs:
     ram: 8192
     cpus: 4
extra-repos:
    - name: epel
      metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
      gpgcheck: 0
    - name: cri-o
      baseurl: https://cbs.centos.org/repos/virt7-container-common-candidate/$basearch/os
      gpgcheck: 0

required: true

timeout: 90m

tests:
  - sh .papr_prepare.sh

artifacts:
  - build.log

context: "CAH smoketested"


---

inherit: true
host:
    distro: fedora/28/cloud
    specs:
        ram: 8192
        cpus: 4
packages:
    - podman
    - buildah
tests:
    - sed 's/^expand-check.*/expand-check=0/g' -i /etc/selinux/semanage.conf
    - yum -y reinstall container-selinux
    - CONTAINER_RUNTIME="podman" sh .papr_prepare.sh
required: false

timeout: 90m
context: "Fedora fedora/28/cloud Podman"

---

container:
    image: registry.fedoraproject.org/fedora:28
tests:
    - sh contrib/build_rpm.sh
required: true
context: "Fedora RPM regressions"

---

container:
    image: registry.centos.org/centos:7
tests:
    - sh contrib/build_rpm.sh
required: true
context: "CentOS RPM regressions"

---

container:
    image: registry.fedoraproject.org/fedora:28

packages:
    - btrfs-progs-devel
    - glib2-devel
    - glibc-devel
    - glibc-static
    - git
    - go-md2man
    - gpgme-devel
    - libassuan-devel
    - libgpg-error-devel
    - libseccomp-devel
    - libselinux-devel
    - ostree-devel
    - pkgconfig
    - make
    - go-compilers-golang-compiler
    
tests:
    - sh .papr.sh -v -b
required: true
context: "gofmt, lint, and build test"
