branches:
  - master
  - auto
  - try

host:
  distro: Fedora-Atomic-26
  specs:
     ram: 8192

required: true

tests:
  # mount yum repos to inherit injected mirrors from PAPR
  - sestatus
  - cat /proc/cmdline
  - cat /etc/selinux/config
  - docker run --net=host --privileged -v /etc/yum.repos.d:/etc/yum.repos.d.host:ro
    -v /tmp:/tmp -v /var/tmp:/var/tmp
    -v $PWD:/code registry.fedoraproject.org/fedora:26 sh -c
    "cp -fv /etc/yum.repos.d{.host/*.repo,} && /code/.papr.sh"
