branches:
  - master
  - auto
  - try

host:
  distro: fedora/28/atomic
  specs:
     ram: 8192
     cpus: 4
required: true
timeout: 45m

tests:
  - CONTAINER_RUNTIME="podman" sh .papr_prepare.sh

artifacts:
  - build.log

context: "FAH28"
---

host:
  distro: centos/7/atomic/smoketested
  specs:
     ram: 8192
     cpus: 4
extra-repos:
    - name: epel
      metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
      gpgcheck: 0
    - name: cri-o
      baseurl: https://cbs.centos.org/repos/virt7-container-common-candidate/$basearch/os
      gpgcheck: 0

required: true
timeout: 45m

tests:
  - sh .papr_prepare.sh

artifacts:
  - build.log

context: "CAH smoketested"


---

inherit: true
host:
    distro: fedora/28/cloud
    specs:
        ram: 8192
        cpus: 4
extra-repos:
    - name: crio_copr
      baseurl: https://copr-be.cloud.fedoraproject.org/results/baude/Upstream_CRIO_Family/fedora-28-x86_64/
      gpgcheck: 0
packages:
    - podman
tests:
    - CONTAINER_RUNTIME="podman" sh .papr_prepare.sh
required: true
context: "Fedora fedora/28/cloud Podman"

---

inherit: true
host:
    distro: fedora/28/cloud
    specs:
        ram: 8192
        cpus: 4
packages:
    - btrfs-progs-devel
    - atomic-registries
    - bzip2
    - conmon
    - device-mapper-devel
    - findutils
    - git
    - glib2-devel
    - gnupg
    - golang
    - golang-github-cpuguy83-go-md2man
    - gpgme-devel
    - libassuan-devel
    - libseccomp-devel
    - libselinux-devel
    - skopeo-containers
    - runc
    - make
    - ostree-devel
    - python
    - python3-dateutil
    - which
    - procps-ng
    - iptables
    - containernetworking-cni
tests:
    - chmod +x ./.papr_test.sh
    - chcon -t container_share_t ./.papr_test.sh
    - CGROUP_MANAGER=systemd runcon system_u:system_r:spc_t:s0 ./.papr_test.sh
required: false
context: "fedora 28 cloud podman systemd cgroups"
