branches:
  - master
  - auto
  - try

host:
  distro: fedora/27/atomic
  specs:
     ram: 8192

required: true
timeout: 45m

tests:
  - CRIO_ROOT=/var/tmp/checkout PODMAN_BINARY=/usr/bin/podman CONMON_BINARY=/usr/libexec/crio/conmon PAPR=1 sh .papr.sh

packages:
    - bats
    - containernetworking-cni
---

inherit: true
host:
  distro: centos/7/atomic/smoketested
  specs:
     ram: 8192
extra-repos:
    - name: epel
      metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
      gpgcheck: 0

context: centos/7/atomic/smoketested
